version = "3.7.15"
runner.dialect = scala3

# Number of maximum characters in a column
maxColumn = 120

trailingCommas = always
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly


assumeStandardLibraryStripMargin = true

align.stripMargin = true
align.preset = more

