base {
  timeli-fe-url: "http://localhost:5127"
}

server {
  host: "0.0.0.0"
  port: 4040
}

db {
  host: "0.0.0.0"
  port: 5432
  username: "postgres"
  password: ${?DB_PASSWORD} 
  database: "timeli"
}

redis {
  url: "redis://localhost:6379"
}

jwt {
  access-token-secret: ${?JWT_ACCESS_TOKEN_SECRET}
  access-token-exp-time: 900
  refresh-token-secret: ${?JWT_REFRESH_TOKEN_SECRET}
  refresh-token-exp-time: 3600
  password-reset-token-secret: ${?JWT_PASSWORD_RESET_TOKEN_SECRET}
  password-reset-token-exp-time: 1800
}

mail {
  host: "email-smtp.ap-southeast-2.amazonaws.com" 
  port: 587 
  username: ${?MAIL_USERNAME}
  password: ${?MAIL_PASSWORD}
}

seeder {
  user-email: ${?USER_EMAIL} 
  user-password: ${?USER_PASSWORD}
}




