server {
  host: "0.0.0.0"
  port: 4040
}

db {
  host: "0.0.0.0"
  port: 5432
  username: "postgres"
  password: ${?DB_PASSWORD} 
  database: "timeli"
}

jwt {
  access-token-secret: ${?JWT_ACCESS_TOKEN_SECRET}
  access-token-exp-time: 900
  refresh-token-secret: ${?JWT_REFRESH_TOKEN_SECRET}
  refresh-token-exp-time: 3600
}



