
CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY, 
  name VARCHAR(50) UNIQUE NOT NULL,
  mask TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  roleId UUID,
  FOREIGN KEY (roleId) REFERENCES roles(id) ON DELETE SET DEFAULT
);




